In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
# Print the versions of tensorlfow and keras

print (tf.__version__)

print (keras.__version__)


2.0.0
2.2.4-tf


In [3]:
# Lets load fashion MNIST contains 70,000 gray scale images of 28 x 28 pixels 
# Pixel intensities vary from 0 to 255
# 0 - white , 255 - gray

fashion_mnist = keras.datasets.fashion_mnist

(X_train_full,y_train_full), (X_test,y_test) = fashion_mnist.load_data()



In [4]:
# Lets check the shape of X_train and X_test

print (X_train_full.shape)

print (X_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [5]:
# Create the validation set
#X_valid = X_train_full[:5000]
#Y_valid = Y_train_full[:5000]
#X_train = X_train_full[5000:]
#Y_train = Y_train_full[5000:]
X_valid, X_train = X_train_full[:5000] / 255.0, X_train_full[5000:] / 255.0
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]
X_test = X_test / 255.0

In [6]:
# Since we are going train to neural network  we need to scale the pixel intensities between 0 amd 1
# This is required for gradient descent to work

#X_valid = X_valid/255.0
#Y_valid = Y_valid/255.0
#X_train = X_train/255.0
#Y_train = Y_train/255.0
#X_test = X_test/255.0


In [7]:
class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat","Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]

In [8]:
class_names[y_train[0]]

'Coat'

In [9]:
# 4 stands for coat

print (y_train[0])

4


In [10]:
# Building a keras model using sequential API

model = keras.models.Sequential() # Creates Sequential model
model.add(keras.layers.Flatten(input_shape=[28,28])) # Input layer of 28 x 28
model.add(keras.layers.Dense(300, activation="relu")) # Dense layer of 300 neurons
model.add(keras.layers.Dense(100, activation="relu")) # Dense Layer of 100 neurons
model.add(keras.layers.Dense(10,  activation="softmax")) # Dense layer of 10 neurons with softmax activation because we have 10 classes 


In [11]:
# Check the mode built so far

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 300)               235500    
_________________________________________________________________
dense_1 (Dense)              (None, 100)               30100     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010      
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


The first dense layer has 784 × 300 connection weights, plus 300 bias terms, which adds up to 235,500 parameters

In [12]:
# You can see all layers or access the layers individually

model.layers

In [13]:
hidden1 = model.layers[1]

print (hidden1.name)

dense


In [14]:
# Access the weights and biases of any layer using get_weights() method

weights, biases = hidden1.get_weights()

In [15]:
weights.shape # has 784 * 300 connection weights 

(784, 300)

In [16]:
biases.shape # Has 300 biases 

(300,)

In [17]:
# Check the weights
weights

array([[ 0.0558591 , -0.04061107,  0.05752498, ...,  0.0667164 ,
         0.06637913, -0.00724912],
       [ 0.03006566, -0.02547301, -0.01542773, ...,  0.05170052,
         0.00932687,  0.03089765],
       [-0.01349444,  0.06435312,  0.07176194, ..., -0.01910824,
        -0.00092441,  0.00093476],
       ...,
       [-0.06763235,  0.00162117, -0.02850636, ...,  0.03515697,
        -0.07408655, -0.05305213],
       [ 0.02489706, -0.01873919,  0.02838717, ...,  0.03167585,
        -0.06308326, -0.01655463],
       [-0.01124635,  0.03441236,  0.02438602, ...,  0.07373294,
        -0.05673486, -0.05525436]], dtype=float32)

As seen above the weights are initialized randomly. This is important.

If all network weights are intialized to zero then the network will never learn.

Initializing weights randomly helps the network break symmetry and learn.

In [18]:
# Compile the model.
# When compiling, we need to specify loss function, optimizer, and metric

model.compile(loss="sparse_categorical_crossentropy", optimizer ="adam", metrics=["accuracy"])

"sparse_categorical_crossentropy" - Used for loss because we have integer labels i.e classes are exclusive

If instead labels were one hot encoded then we would have used "categorical_crossentropy" loss.

For Binary classification, 

We would use "sigmoid" instead of "softmax" activation in the output layer and while compiling the model we 

would use "binary_crossentropy" loss.

There are obviously other losses and optimizers. The full list is here:

 https://keras.io/losses, 
 
 https://keras.io/optimizers, 
 
 and 
 
 https://keras.io/metrics.

In [ ]:
# Train the model using the fit method

model.fit(X_train,y_train,epochs=30,validation_data=(X_valid,y_valid))

Train on 55000 samples, validate on 5000 samples
Epoch 1/30


Notice that with each epoch the loss reduced and accuracy increased

The training and validation accuracy as 95% and 89.5% respectively.

So there is not much of over fitting going on here





In [1]:
# The model is trained, lets make predictions

X_new = X_test[:3]

y_proba = model.predict(X_new)

print (y_proba.round(3))

NameError: name 'X_test' is not defined

In [ ]:
# Predict classes



y_classes = model.predict_classes(X_new)

print (y_classes)

[9 2 1]


In [ ]:
# Compare prediction with actual classes

y_test[:3]

array([9, 2, 1], dtype=uint8)

In [ ]:
# Get class names
import numpy as np

np.array(class_names)[y_classes]

array(['Ankle boot', 'Pullover', 'Trouser'], dtype='<U11')

In [ ]:
# Save your model

model.save("fashion_mnist.H5")

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: fashion_mnist.H5/assets


In [ ]:
# Loading the saved model


model1 = keras.models.load_model("fashion_mnist.H5")

In [ ]:
# Make predictions using the model you just loaded

y_classes1 = model1.predict_classes(X_new)

In [ ]:
print (y_classes1)

[9 2 1]


As seens above the results are matching. So you just have to compile your model then save it and then load the saved model to keep working.

This is important because training deep learning models is computationally expensive.


# Building a Regression MLP


In [ ]:
from sklearn.datasets import  fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()

# Split into train - test set

X_train_full, X_test, y_train_full, y_test = train_test_split(housing.data,housing.target) 

# Split train set into train and validation sets

X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full)

# Scale the inputs so that SGD algo can train the network

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_valid = scaler.fit_transform(X_valid)
X_test = scaler.fit_transform(X_test)


In [ ]:
# input for the regression model will be all the columns. 
# The input layer of the neural network will therefore have 8 neurons

X_train.shape[1:]

(8,)

In [ ]:
# Define the model structure

model3 = keras.models.Sequential()
model3.add(keras.layers.InputLayer(input_shape=X_train.shape[1:]))
model3.add(keras.layers.Dense(30,activation="relu"))
model3.add(keras.layers.Dense(1))


In [ ]:
# compile the model. Define loss and optimizer

model3.compile(loss="mean_squared_error", optimizer="adam")


In [ ]:
# Train the model

model3.fit(X_train, y_train, epochs=30, validation_data=(X_valid,y_valid))

Train on 11610 samples, validate on 3870 samples
Epoch 1/30
11610/11610 [==============================] - 1s 98us/sample - loss: 1.7897 - val_loss: 0.7786
Epoch 2/30
11610/11610 [==============================] - 1s 48us/sample - loss: 0.6599 - val_loss: 0.5823
Epoch 3/30
11610/11610 [==============================] - 1s 48us/sample - loss: 0.5038 - val_loss: 0.4924
Epoch 4/30
11610/11610 [==============================] - 1s 48us/sample - loss: 0.4336 - val_loss: 0.4525
Epoch 5/30
11610/11610 [==============================] - 1s 48us/sample - loss: 0.4078 - val_loss: 0.4399
Epoch 6/30
11610/11610 [==============================] - 1s 52us/sample - loss: 0.3960 - val_loss: 0.4327
Epoch 7/30
11610/11610 [==============================] - 1s 48us/sample - loss: 0.3887 - val_loss: 0.4222
Epoch 8/30
11610/11610 [==============================] - 1s 53us/sample - loss: 0.3816 - val_loss: 0.4214
Epoch 9/30
11610/11610 [==============================] - 1s 50us/sample - loss: 0.3787 - val_l

In [ ]:
X_new = X_test[:3]

y_pred = model3.predict(X_new)

y_pred

array([[1.7664998],
       [1.6733724],
       [2.2074418]], dtype=float32)

# Complex models using Functional API

We have seen sequential networks so far. 

Next we look at non-sequential neural networks.

Complex non-sequential models can be built using Keras's Functional API



![image.png](attachment:image.png)

The architecture shown above is for Wide and Deep Neural Network proposed by Google Researchers in 2016.

It connects all or part of the inputs directly to the output layer, as shown above.

This architecture makes it possible for the neural network to learn both deep patterns (using the deep path) and simple rules (through the short path).

In contrast, a regular MLP forces all the data to flow through the full stack of layers; thus, simple patterns in the data may end up being distorted by this sequence of transformations.

The paper is available here: https://arxiv.org/abs/1606.07792


In [ ]:
# Lets build the wide and deep Neural Network for the california housing model

input_ = keras.layers.Input(shape=X_train.shape[1:])
hidden1 = keras.layers.Dense(30, activation="relu")(input_)
hidden2 = keras.layers.Dense(30, activation="relu")(hidden1)
concat = keras.layers.Concatenate()([input_, hidden2]) # Mixes the input layer with output of hidden2 layer
output = keras.layers.Dense(1)(concat)
model = keras.Model(inputs=[input_], outputs=[output])



The next steps remain unchanged i.e compile, fit, predict

# Multi-input Architectures

Use these architectures you can feed a subset of features through the wide path and a different subset through the deep path.


![image.png](attachment:image.png)

In [ ]:
# California housing problem
# first 5 features (0-4) --> Wide path
# Six features (2-7) --> Deep path

input_A = keras.layers.Input(shape=[5], name="wide_input")
input_B = keras.layers.Input(shape=[6], name="deep_input")
hidden1 = keras.layers.Dense(30, activation="relu")(input_B)
hidden2 = keras.layers.Dense(30, activation="relu")(hidden1)
concat = keras.layers.concatenate([input_A, hidden2])
output = keras.layers.Dense(1, name="output")(concat)
model4 = keras.Model(inputs=[input_A, input_B], outputs=[output])


In [ ]:
# Compile the model.

model4.compile(loss="mse", optimizer="adam")

# Fit the model. Remember we now have to pass 2 inputs when we fit the model.
# We need to split X_train, X_valid, X_test, X_new into two separate inputs

X_train_A, X_train_B = X_train[:,:5], X_train[:,2:]
X_valid_A, X_valid_B = X_valid[:,:5], X_valid[:,2:]
X_test_A, X_test_B = X_test[:,:5], X_test[:,2:]
X_new_A, X_new_B = X_test_A[:3], X_test_B[:3]



In [ ]:
# Fit the model. Note: fit method returns an object containing history. We will see its usage

history = model4.fit((X_train_A, X_train_B), y_train, epochs=15,
                    validation_data=((X_valid_A, X_valid_B), y_valid))



Train on 11610 samples, validate on 3870 samples
Epoch 1/15
11610/11610 [==============================] - 1s 125us/sample - loss: 1.4977 - val_loss: 0.6243
Epoch 2/15
11610/11610 [==============================] - 1s 60us/sample - loss: 0.4911 - val_loss: 0.4808
Epoch 3/15
11610/11610 [==============================] - 1s 64us/sample - loss: 0.4279 - val_loss: 0.4463
Epoch 4/15
11610/11610 [==============================] - 1s 61us/sample - loss: 0.4078 - val_loss: 0.4364
Epoch 5/15
11610/11610 [==============================] - 1s 65us/sample - loss: 0.4002 - val_loss: 0.4374
Epoch 6/15
11610/11610 [==============================] - 1s 62us/sample - loss: 0.3907 - val_loss: 0.4275
Epoch 7/15
11610/11610 [==============================] - 1s 66us/sample - loss: 0.3819 - val_loss: 0.4141
Epoch 8/15
11610/11610 [==============================] - 1s 60us/sample - loss: 0.3692 - val_loss: 0.4339
Epoch 9/15
11610/11610 [==============================] - 1s 63us/sample - loss: 0.3648 - val_

In [ ]:
# Evaluate and predict


mse_test = model4.evaluate((X_test_A, X_test_B), y_test)

y_pred = model.predict((X_new_A, X_new_B))

print (y_pred)

print (mse_test)

5160/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[[-0.17300448]
 [-0.0865384 ]
 [-0.48652852]]
0.34560617462609167


# Multi-output Neural Network

Just like you had multiple inputs you might need a deep neural network to produce multiple outputs.

For example, in image recognition a neural network must often detect an object such as a car in the image which is a classification task and the same network must also output the location of the object (co-ordinates of the center, height, width of the box).

This is an example of a classifier and a regression model. The neural network in such a case will require multiple outputs.



![image.png](attachment:image.png)

In [ ]:
# Lets build the above architecture for California housing data set

input_A = keras.layers.Input(shape=[5], name="wide_input")
input_B = keras.layers.Input(shape=[6], name="deep_input")
hidden1 = keras.layers.Dense(30, activation="relu")(input_B)
hidden2 = keras.layers.Dense(30, activation="relu")(hidden1)
concat = keras.layers.concatenate([input_A, hidden2])
output = keras.layers.Dense(1,name="main_output")(concat)
aux_output = keras.layers.Dense(1,name="aux_output")(hidden2)
model5 = keras.Model(inputs=[input_A,input_B],outputs=[output,aux_output]) # Passing 2 inputs and 2 outputs

In [ ]:
# While compiling the model, we will need 2 losses.
# Keras will add the losses together to compute the total loss.
# However, in most cases we care more about the main loss than the auxilary loss. This is done by assigning a weight to the loss


model5.compile(loss=["mse","mse"],optimizer="adam", loss_weights=[0.9,0.1])





In [ ]:
# When fitting the model, we need to pass y_train twice because in this model main output and auxillary output are measuring the same thing

history = model5.fit([X_train_A,X_train_B],[y_train,y_train],epochs=30,validation_data=([X_valid_A,X_valid_B],[y_valid,y_valid]))
                     
                     


Train on 11610 samples, validate on 3870 samples
Epoch 1/30
11610/11610 [==============================] - 2s 161us/sample - loss: 1.3677 - main_output_loss: 1.2854 - aux_output_loss: 2.1045 - val_loss: 0.5912 - val_main_output_loss: 0.5456 - val_aux_output_loss: 1.0015
Epoch 2/30
11610/11610 [==============================] - 1s 76us/sample - loss: 0.4979 - main_output_loss: 0.4701 - aux_output_loss: 0.7460 - val_loss: 0.4926 - val_main_output_loss: 0.4694 - val_aux_output_loss: 0.7009
Epoch 3/30
11610/11610 [==============================] - 1s 73us/sample - loss: 0.4297 - main_output_loss: 0.4107 - aux_output_loss: 0.6015 - val_loss: 0.4694 - val_main_output_loss: 0.4510 - val_aux_output_loss: 0.6348
Epoch 4/30
11610/11610 [==============================] - 1s 72us/sample - loss: 0.4110 - main_output_loss: 0.3952 - aux_output_loss: 0.5522 - val_loss: 0.4485 - val_main_output_loss: 0.4315 - val_aux_output_loss: 0.6011
Epoch 5/30
11610/11610 [==============================] - 1s 73us/

In [ ]:
# Use Evaluate method to calculate the total, main and auxilary loss

total_loss, main_loss, aux_loss = model5.evaluate([X_test_A,X_test_B],[y_test,y_test])

5160/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

In [ ]:
print (total_loss,main_loss,aux_loss)

0.34872430664624354 0.34225875 0.41587195


In [ ]:
# Predict using the model built

y_pred_main, y_pred_aux = model5.predict([X_new_A,X_new_B])

# Callbacks 

The fit() method has a callbacks argument which is a list of operations you can call at the following points:

1) Start and end of training

2) Start and end of each epoch

3) Before or after processesing each mini-batch


In [ ]:
# For example: ModelCheckpoint callback saves weights of your best model on the validation data

checkpoint_cb = keras.callbacks.ModelCheckpoint("best_model5.h5",save_best_only=True)

history = model5.fit([X_train_A,X_train_B],[y_train,y_train],epochs=30,
                     validation_data=([X_valid_A,X_valid_B],[y_valid,y_valid]),
                     callbacks=[checkpoint_cb])



Train on 11610 samples, validate on 3870 samples
Epoch 1/30
11610/11610 [==============================] - 1s 81us/sample - loss: 0.3058 - main_output_loss: 0.3012 - aux_output_loss: 0.3490 - val_loss: 0.4095 - val_main_output_loss: 0.4005 - val_aux_output_loss: 0.4905
Epoch 2/30
11610/11610 [==============================] - 1s 79us/sample - loss: 0.3006 - main_output_loss: 0.2952 - aux_output_loss: 0.3485 - val_loss: 0.5078 - val_main_output_loss: 0.4985 - val_aux_output_loss: 0.5917
Epoch 3/30
11610/11610 [==============================] - 1s 76us/sample - loss: 0.2975 - main_output_loss: 0.2924 - aux_output_loss: 0.3436 - val_loss: 0.4045 - val_main_output_loss: 0.3955 - val_aux_output_loss: 0.4851
Epoch 4/30
11610/11610 [==============================] - 1s 77us/sample - loss: 0.2990 - main_output_loss: 0.2940 - aux_output_loss: 0.3436 - val_loss: 0.4098 - val_main_output_loss: 0.4011 - val_aux_output_loss: 0.4884
Epoch 5/30
11610/11610 [==============================] - 1s 75us/s

In [ ]:
# Load the model that performed best on the validation data

model6 = keras.models.load_model("best_model5.h5")

In [ ]:
# Early Stopping can be implemented by using EarlyStopping callback
# This callback will interrupt training when it measures no progress on the validation set for a number of epochs 
# This is defined by the patient argument


early_stopping_cb = keras.callbacks.EarlyStopping(patience=10,restore_best_weights=True)


# You can now train the model for a large number of epochs without worrying about wasting time

# Training will stop automatically when there is improvement for 10 epochs and the best model will be saved

history = model5.fit([X_train_A,X_train_B],[y_train,y_train],epochs=100,
                     validation_data=([X_valid_A,X_valid_B],[y_valid,y_valid]),
                     callbacks=[early_stopping_cb])









Train on 11610 samples, validate on 3870 samples
Epoch 1/100
11610/11610 [==============================] - 1s 83us/sample - loss: 0.2875 - main_output_loss: 0.2826 - aux_output_loss: 0.3306 - val_loss: 0.4388 - val_main_output_loss: 0.4295 - val_aux_output_loss: 0.5225
Epoch 2/100
11610/11610 [==============================] - 1s 75us/sample - loss: 0.2897 - main_output_loss: 0.2852 - aux_output_loss: 0.3292 - val_loss: 0.3969 - val_main_output_loss: 0.3878 - val_aux_output_loss: 0.4792
Epoch 3/100
11610/11610 [==============================] - 1s 75us/sample - loss: 0.2837 - main_output_loss: 0.2789 - aux_output_loss: 0.3267 - val_loss: 0.3933 - val_main_output_loss: 0.3849 - val_aux_output_loss: 0.4695
Epoch 4/100
11610/11610 [==============================] - 1s 81us/sample - loss: 0.2867 - main_output_loss: 0.2820 - aux_output_loss: 0.3288 - val_loss: 0.3746 - val_main_output_loss: 0.3662 - val_aux_output_loss: 0.4498
Epoch 5/100
11610/11610 [==============================] - 1s 7

As you can see above the training actually stopped at the Epoch 14 automatically
